name: Source branch
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check on proper branch
      if: github.head_ref != 'v1-next'
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed(`PRs for latest-stable must come from v1-next, but branch is ${{ github.head_ref }}`)