name: Selftest

on: pull_request

jobs:
  alr-install:
    name: ${{ matrix.os }}, cache=${{ matrix.cached }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-latest
          - ubuntu-latest
          - windows-latest
        cached:
          - false
          - true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Selftest
        uses: ./ # Uses the action code from the PR itself
        with:
          # One binary and one source crate. We could use a lighter binary
          # crate prepared to this effect... TODO.
          crates: gprbuild hello
          cache: ${{ matrix.cached }}

      - name: Run check
        shell: bash
        run: |
          which gprbuild && \
          gprbuild --version && \
          hello | grep "Hello, world!"
