name: Selftest

on: pull_request

jobs:
  alr-install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cached: [false, true]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Selftest
        uses: ./ # Uses the action code from the PR itself
        with:
          crates: gprbuild
          # This can be changed to a more lightweight crate (hello)
          # once we can install indexed releases.
          cache: ${{ matrix.cached }}

      - name: Run check
        shell: bash
        run: |
          which gprbuild
          gprbuild --version