name: Selftest

on: pull_request

jobs:
  alr-install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:      
      - uses: alire-project/alr-install@v1-next
        with:
          crates: gprbuild
          # This can be changed to a more lightweight crate (hello) 
          # once we can install indexed releases.
          cache: false # Don't use cache for testing

      - name: Run check
        shell: bash
        run: |
          which gprbuild
          gprbuild --version